### ISSUE TITLE
update to rust-1.7.0

### ISSUE THREAD

**Issue by jmesmon** [jmesmon/meta-rust#27]

**Comment by kteza1** [comment]
:+1: Waiting for this

**Comment by derekstraka** [comment]
We have a preliminary PR up [here](https://github.com/starlab-io/meta-rust/pull/10) for rust 1.7.0

Once we do a bit more validation, I'll make a PR into here too. (early testing is always appreciated :smile: )

**Comment by posborne** [comment]
@derekstraka @cardoe Thanks for putting together this change and the discussions with the rust core team (hopefully in the next few versions we can eliminate the need to patch the rust source completely).  I tested with this branch in combination with [this image](https://github.com/posborne/rustbone) and things build and seem to work properly.

:+1: for the change -- I think it makes sense to open up a PR against this repo sooner rather than later.
